apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: flight-web-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: flight-service-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: flight-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-service-app
  template:
    metadata:
      labels:
        app: flight-service-app
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: flight-service-app
          image: lehudocker/flight-web-staging-app:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: docker-registry-secret